### PR TITLE
Issues 104, 105 and 106 (hot deployment)

### PR DESCRIPTION
**Pull request by hannes-ucsc**

### CODE REVIEW

**Comment by hannes-ucsc** [comment]
Jenkins, test this please.

**Comment by hannes-ucsc** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.cgcloud.info//job/jobtree/26/

**Comment by hannes-ucsc** [comment]
psutil was missing on the slave

**Comment by hannes-ucsc** [comment]
Jenkins, test this please.

**Comment by hannes-ucsc** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.cgcloud.info//job/jobtree/27/

**Comment by hannes-ucsc** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.cgcloud.info//job/jobtree/28/

**Comment by hannes-ucsc** [comment]
psutil depends on python-dev package

**Comment by hannes-ucsc** [comment]
Jenkins, test this please.

**Comment by hannes-ucsc** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.cgcloud.info//job/jobtree/29/

**Comment by hannes-ucsc** [comment]
The tests are currently resulting in a hang. In 95889b72ce29f11dd8689b719430d5e0db95d1c2 I introduced a bug in singleMachine batch system that could cause jobs to be ignored. This is fixed in 7a969e9ba982be6acc62735b91bb2022f10d44a5 on master which I am testing now. Stay tuned.

**Comment by hannes-ucsc** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.cgcloud.info//job/jobtree/32/

**Comment by hannes-ucsc** [comment]
Sorry, was delusional with my commit. Will fix soon.

**Comment by cket** [comment]
The build failure was my fault - I changed the batch system constructor arguments and forgot to modify john's tests with the new parameter

**Comment by hannes-ucsc** [comment]
Jenkins, test this please.

**Pull request merged**
